spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

spring.cloud.consul:
  host: localhost
  port: 8500
  discovery:
    enabled: true