spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=petar.mitrovish@gmail.com
spring.mail.password=dozt mbgl sokw cslh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

