spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5434/core_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

spring.cloud.consul:
  host: localhost
  port: 8500
  discovery:
    enabled: true